// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {categories} from '../models';

export function Create(arg1:categories.CategoryCreateRequest):Promise<number>;

export function Delete(arg1:number):Promise<void>;

export function GetAll():Promise<Array<categories.Category>>;

export function GetByID(arg1:number):Promise<categories.Category>;

export function Update(arg1:number,arg2:categories.CategoryUpdateRequest):Promise<void>;
