// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1) {
  return window['go']['products']['Controller']['Create'](arg1);
}

export function Delete(arg1) {
  return window['go']['products']['Controller']['Delete'](arg1);
}

export function GetAll() {
  return window['go']['products']['Controller']['GetAll']();
}

export function GetByID(arg1) {
  return window['go']['products']['Controller']['GetByID'](arg1);
}

export function Update(arg1, arg2) {
  return window['go']['products']['Controller']['Update'](arg1, arg2);
}
