// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {products} from '../models';

export function Create(arg1:products.CreateRequest):Promise<number>;

export function Delete(arg1:number):Promise<void>;

export function GetAll():Promise<Array<products.Product>>;

export function GetByID(arg1:number):Promise<products.Product>;

export function Update(arg1:number,arg2:products.CreateRequest):Promise<void>;
